openapi: 3.0.0
info:
  title: EB-1A Visa Application API
  version: 1.0.0
  description: API to handle the processing and tracking of EB-1A visa applications for individuals with extraordinary ability in their field of expertise.
  termsOfService: 'http://example.com/terms/'
  contact:
    name: Support Team
    email: support@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /applications:
    post:
      summary: Submit EB-1A visa application
      description: Endpoint to submit a new EB-1A visa application for an individual with extraordinary ability.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EB1AApplicationRequest'
      responses:
        '201':
          description: Application submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EB1AApplicationResponse'
        '400':
          description: Bad request, details in response

  /applications/{applicationId}:
    get:
      summary: Get application status
      description: Endpoint to check the status of an EB-1A visa application.
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationStatusResponse'
        '404':
          description: Application not found

  /rfe/{applicationId}:
    post:
      summary: Submit RFE response
      description: Endpoint for submitting a response to a Request for Evidence for an EB-1A application.
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RFEResponse'
      responses:
        '200':
          description: RFE response submitted successfully
        '400':
          description: Bad request, details in response
        '404':
          description: Application not found

components:
  schemas:
    EB1AApplicationRequest:
      type: object
      required:
        - applicantName
        - fieldOfExpertise
        - evidence
      properties:
        applicantName:
          type: string
        fieldOfExpertise:
          type: string
        evidence:
          type: array
          items:
            type: string
          description: List of evidence documents supporting the application.

    EB1AApplicationResponse:
      type: object
      properties:
        applicationId:
          type: string
          description: Unique identifier for the submitted application.

    ApplicationStatusResponse:
      type: object
      properties:
        applicationId:
          type: string
        status:
          type: string
          description: Current status of the application.
        details:
          type: string
          description: Detailed status message, if available.

    RFEResponse:
      type: object
      required:
        - responseCriteria
      properties:
        responseCriteria:
          type: array
          items:
            type: object
            required:
              - criterion
              - evidence
            properties:
              criterion:
                type: string
                description: Specific EB-1A criterion being addressed.
              evidence:
                type: string
                description: Description or reference to evidence submitted in response to the RFE.
